title: Marc McHardy. Product designer.
short: Web, app, and interactive design, visual design, development
involvement_title: My involvement in this project
email: hi@marcmchardy.com
description: Product designer and problem solver. 10+ years experience designing and building websites, apps, and other interactive experiences that are clear, easy to use, and a little bit fun. From helping to shape your idea through to UX, design, and build, I can help you out.
baseurl: "" 
url: "https://marcmchardy.com"
twitter_username: marc_mchardy
github_username:  marcmchardy

theme: null
destination: docs

# Build settings
markdown: kramdown
plugins:
  - jekyll-autoprefixer
  - jekyll-inline-svg

autoprefixer:
  browsers:
    - last 2 versions

sass:
  sass_dir: _sass
  style: compressed
  
svg:
  optimize: true

permalink: /:categories/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - css
  - recipes
  - package.json
  - package-lock.json
