# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
short: Web, app, and interactive design, visual design, development
involvement_title: My involvement in this project
email: hi@marcmchardy.com
description: >- # this means to ignore newlines until "baseurl:"
  Web, app, and interactive design, visual design, development.
  Marc is a digital product designer and problem solver. With over ten 
  years in the industry he creates websites, apps, and other experiences 
  that are clear, easy to use, and a little bit fun.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marcmchardy.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marc_mchardy
github_username:  marcmchardy

theme: null

# Build settings
markdown: kramdown
plugins:
  - jekyll-autoprefixer
  - jekyll-inline-svg

autoprefixer:
  browsers:
    - last 2 versions

sass:
  sass_dir: _sass
  style: compressed
  
svg:
  optimize: true

permalink: /:categories/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yonder
  - css
  - recipes
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
